# Evaluating learning methods

## 1) Evaluating a classifier

In [2]:
import numpy as np


def score(h, test_X, test_y):
    """
    Returns the percentage of correctly classified 
    examples as a decimal between 0 and 1
    """
    raise NotImplemented

    
def eval_classifier(h, D):
    test_X, test_y = D
    return score(h, test_X, test_y)




## 2) Evaluating a learning algorithm

In [4]:
def eval_learning_alg(L, G, n):
    # draw a set of n training examples (points and labels)
    train_X, train_y = G(n)
    # run L
    h = L(train_X, train_y)
    # evaluate using your classifier scoring procedure, on some new labeled data
    score = 0
    for i in range(10):
        test_data = G(n) # draw new set of test data
        score += eval_classifier(h, test_data)
    return score/10

In addition to the Numpy functions and features mentioned in hw 1, here are some you should be familiar with for this assignment:

    np.argmax
    np.array_split, look at the axis argument
    np.concatenate, look at the axis argument
    np.zeros
    numpy.ndarray.shape
    numpy logic functions e.g. np.array([[1, 2],[3, 4]]) == 3



In [7]:
a = np.array([1, 2, 3]).T

a[np.argmax(a)]

3

In [30]:
a, b = np.array([1, 2, 3, 4]), np.array([[4, 5, 6, 7], [1, 2, 3, 4]])
np.array_split(a, 2), np.array_split(b, 2, axis=0)

([array([1, 2]), array([3, 4])],
 [array([[4, 5, 6, 7]]), array([[1, 2, 3, 4]])])

In [32]:
c = np.array([
    [
        [1, 2],
        [3, 4],
    ],
    [
        [5, 6],
        [7, 8],
    ],
])
np.concatenate(c, axis=1), np.split(np.concatenate(c), 2, axis=0)

(array([[1, 2, 5, 6],
        [3, 4, 7, 8]]),
 [array([[1, 2],
         [3, 4]]),
  array([[5, 6],
         [7, 8]])])

In [33]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [35]:
l = np.array([
    [1, 2],
    [3, -1],
])
l == 3, l>1

(array([[False, False],
        [ True, False]]),
 array([[False,  True],
        [ True, False]]))