In [1]:
import sys
sys.path.append('../..')

from practice import utils

import numpy as np
import matplotlib.pyplot as plt


In [2]:
def perceptron_through_the_origin(x: np.array, y: np.array, t: int) -> tuple[np.array]:
    """
    Perceptron learning algorithm.
    returns th.
    """
    th = utils.rv([0, 0]) # 2*1
    k = 0
    for i in range(t):
        converged = True
        for j in range(x.shape[1]):
            yj = y[j]
            xj = x[:, j:j+1]
            r = yj * np.dot(th.T, xj)  
            if r <= 0:
                k+=1
                th = th + yj * xj
                converged = False
                print(th)
        if converged:
            return th, k, i+1
    return th, k, t


In [3]:
def print_alg_info(th, k, i):
    print('th:', th)
    print('mistakes', k)
    print('iterations:', i)

x = np.array([
    [1, 0, -1.5],
    [-1, 1, -1],
])
y = np.array([1, -1, 1])

th, k, i = perceptron_through_the_origin(x, y, 100)
print_alg_info(th, k, i)

[[ 1.]
 [-1.]]
[[-0.5]
 [-2. ]]
th: [[-0.5]
 [-2. ]]
mistakes 2
iterations: 2


1.1c) How many mistakes does the algorithm make if it starts with data point x(2)x^{(2)}x(2) (and then does x(3)x^{(3)}x(3) and x(1)x^{(1)}x(1))? 

In [4]:
x = np.array([
    [0, -1.5, 1],
    [1,  -1, -1],
])
y = np.array([-1, 1, 1])

th, k, i = perceptron_through_the_origin(x, y, 100)
print_alg_info(th, k, i)


[[ 0.]
 [-1.]]
th: [[ 0.]
 [-1.]]
mistakes 1
iterations: 2


1.1d) Again, if it starts with data point x(2)x^{(2)}x(2) (and then does x(3)x^{(3)}x(3) and x(1)x^{(1)}x(1)), which plot(s) correspond to the progression of the hyperplane as the algorithm cycles? Ignore the initial 0 weights. 

## 1.2) Take 2

In [5]:

x = np.array([
    [1, 0, -10],
    [-1, 1, -1],
])
y = np.array([1, -1, 1])


th, k, i = perceptron_through_the_origin(x, y, 100)
print_alg_info(th, k, i)

[[ 1]
 [-1]]
[[-9]
 [-2]]
[[-8]
 [-3]]
[[-7]
 [-4]]
[[-6]
 [-5]]
[[-5]
 [-6]]
th: [[-5]
 [-6]]
mistakes 6
iterations: 6


In [6]:
x = np.array([
    [0, 1, -10],
    [1, -1, -1],
])
y = np.array([-1, 1, 1])


th, k, i = perceptron_through_the_origin(x, y, 100)
print_alg_info(th, k, i)

[[ 0]
 [-1]]
th: [[ 0]
 [-1]]
mistakes 1
iterations: 2


In [7]:



def perceptron_through_the_origin_modified(x: np.array, y: np.array, t: int) -> tuple[np.array]:
    """
    Perceptron learning algorithm.
    returns th.
    """
    th = utils.rv([1000, -1000]) # 2*1
    k = 0
    for i in range(t):
        converged = True
        for j in range(x.shape[1]):
            yj = y[j]
            xj = x[:, j:j+1]
            r = yj * np.dot(th.T, xj)  
            if r <= 0:
                k+=1
                th = th + yj * xj
                converged = False
                print(th)
        if converged:
            return th, k, i+1
    return th, k, t


In [8]:
x = np.array([
    [1, 0, -1.5],
    [-1, 1, -1],
])
y = np.array([1, -1, 1])


th, k, i = perceptron_through_the_origin_modified(x, y, 100)
print_alg_info(th, k, i)

[[  998.5]
 [-1001. ]]
[[  997.]
 [-1002.]]
[[  995.5]
 [-1003. ]]
[[  994.]
 [-1004.]]
[[  992.5]
 [-1005. ]]
[[  991.]
 [-1006.]]
[[  989.5]
 [-1007. ]]
[[  988.]
 [-1008.]]
[[  986.5]
 [-1009. ]]
[[  985.]
 [-1010.]]
[[  983.5]
 [-1011. ]]
[[  982.]
 [-1012.]]
[[  980.5]
 [-1013. ]]
[[  979.]
 [-1014.]]
[[  977.5]
 [-1015. ]]
[[  976.]
 [-1016.]]
[[  974.5]
 [-1017. ]]
[[  973.]
 [-1018.]]
[[  971.5]
 [-1019. ]]
[[  970.]
 [-1020.]]
[[  968.5]
 [-1021. ]]
[[  967.]
 [-1022.]]
[[  965.5]
 [-1023. ]]
[[  964.]
 [-1024.]]
[[  962.5]
 [-1025. ]]
[[  961.]
 [-1026.]]
[[  959.5]
 [-1027. ]]
[[  958.]
 [-1028.]]
[[  956.5]
 [-1029. ]]
[[  955.]
 [-1030.]]
[[  953.5]
 [-1031. ]]
[[  952.]
 [-1032.]]
[[  950.5]
 [-1033. ]]
[[  949.]
 [-1034.]]
[[  947.5]
 [-1035. ]]
[[  946.]
 [-1036.]]
[[  944.5]
 [-1037. ]]
[[  943.]
 [-1038.]]
[[  941.5]
 [-1039. ]]
[[  940.]
 [-1040.]]
[[  938.5]
 [-1041. ]]
[[  937.]
 [-1042.]]
[[  935.5]
 [-1043. ]]
[[  934.]
 [-1044.]]
[[  932.5]
 [-1045. ]]
[[  931.]

# 3) Dual View

In [9]:
x = np.array([
    [-3, 2],
    [-1, 1],
    [-1, -1],
    [2, 2],
    [1, -1],
]).T
y = np.array([1, -1, -1, -1,-1])


def perceptron_through_the_origin(x: np.array, y: np.array, t: int, th=None) -> tuple[np.array]:
    """
    Perceptron learning algorithm.
    returns th.
    """
    if th is None:
        th = utils.rv([0, 0]) # 2*1
    k = 0
    for i in range(t):
        converged = True
        for j in range(x.shape[1]):
            yj = y[j]
            xj = x[:, j:j+1]
            r = yj * np.dot(th.T, xj)  
            if r <= 0:
                k+=1
                th = th + yj * xj
                converged = False
                print(th)
        if converged:
            return th, k, i+1
    return th, k, t


def perceptron(x: np.array, y: np.array, t: int) -> tuple[np.array]:
    """
    Perceptron learning algorithm.
    returns tuple of th and th0.
    """
    th = utils.rv([0, 0]) # 2*1
    th0 = 0 # 1*1
    k = 0
    for i in range(t):
        converged =True
        for j in range(x.shape[1]):
            yj = y[j]
            xj = x[:, j:j+1]
            r = yj * (np.dot(th.T, xj) + th0)  
            if r <= 0:
                k+=1
                th = th + yj * xj
                th0 = th0 + yj
                converged = False
        if converged:
            return th, th0, k, i+1
    return th, th0, k, t




th, th0, k, i = perceptron(x, y, 100)
print_alg_info((th, th0), k, i)

th: (array([[-2],
       [ 0]]), -5)
mistakes 9
iterations: 5


# 4) Decision Boundaries

## 4.1) AND

In [10]:
x = np.array([
    [0, 0, 0],
    [1, 0, 0],
    [0, 1, 0],
    [0, 0, 1],
    [1, 1, 0],
    [1, 0, 1],
    [0, 1, 1],
    [1, 1, 1],
]).T 
y = np.array([-1, -1, -1, -1, -1, -1, -1, 1])

res = perceptron_through_the_origin(x, y, 200, utils.rv([0, 0, 0]))


[[0]
 [0]
 [0]]
[[-1]
 [ 0]
 [ 0]]
[[-1]
 [-1]
 [ 0]]
[[-1]
 [-1]
 [-1]]
[[0]
 [0]
 [0]]
[[0]
 [0]
 [0]]
[[-1]
 [ 0]
 [ 0]]
[[-1]
 [-1]
 [ 0]]
[[-1]
 [-1]
 [-1]]
[[0]
 [0]
 [0]]
[[0]
 [0]
 [0]]
[[-1]
 [ 0]
 [ 0]]
[[-1]
 [-1]
 [ 0]]
[[-1]
 [-1]
 [-1]]
[[0]
 [0]
 [0]]
[[0]
 [0]
 [0]]
[[-1]
 [ 0]
 [ 0]]
[[-1]
 [-1]
 [ 0]]
[[-1]
 [-1]
 [-1]]
[[0]
 [0]
 [0]]
[[0]
 [0]
 [0]]
[[-1]
 [ 0]
 [ 0]]
[[-1]
 [-1]
 [ 0]]
[[-1]
 [-1]
 [-1]]
[[0]
 [0]
 [0]]
[[0]
 [0]
 [0]]
[[-1]
 [ 0]
 [ 0]]
[[-1]
 [-1]
 [ 0]]
[[-1]
 [-1]
 [-1]]
[[0]
 [0]
 [0]]
[[0]
 [0]
 [0]]
[[-1]
 [ 0]
 [ 0]]
[[-1]
 [-1]
 [ 0]]
[[-1]
 [-1]
 [-1]]
[[0]
 [0]
 [0]]
[[0]
 [0]
 [0]]
[[-1]
 [ 0]
 [ 0]]
[[-1]
 [-1]
 [ 0]]
[[-1]
 [-1]
 [-1]]
[[0]
 [0]
 [0]]
[[0]
 [0]
 [0]]
[[-1]
 [ 0]
 [ 0]]
[[-1]
 [-1]
 [ 0]]
[[-1]
 [-1]
 [-1]]
[[0]
 [0]
 [0]]
[[0]
 [0]
 [0]]
[[-1]
 [ 0]
 [ 0]]
[[-1]
 [-1]
 [ 0]]
[[-1]
 [-1]
 [-1]]
[[0]
 [0]
 [0]]
[[0]
 [0]
 [0]]
[[-1]
 [ 0]
 [ 0]]
[[-1]
 [-1]
 [ 0]]
[[-1]
 [-1]
 [-1]]
[[0]
 [0]
 [0]]
[[0]
 [0]
 [0]]
[[-1]

 [-1]]
[[0]
 [0]
 [0]]
[[0]
 [0]
 [0]]
[[-1]
 [ 0]
 [ 0]]
[[-1]
 [-1]
 [ 0]]
[[-1]
 [-1]
 [-1]]
[[0]
 [0]
 [0]]
[[0]
 [0]
 [0]]
[[-1]
 [ 0]
 [ 0]]
[[-1]
 [-1]
 [ 0]]
[[-1]
 [-1]
 [-1]]
[[0]
 [0]
 [0]]
[[0]
 [0]
 [0]]
[[-1]
 [ 0]
 [ 0]]
[[-1]
 [-1]
 [ 0]]
[[-1]
 [-1]
 [-1]]
[[0]
 [0]
 [0]]
[[0]
 [0]
 [0]]
[[-1]
 [ 0]
 [ 0]]
[[-1]
 [-1]
 [ 0]]
[[-1]
 [-1]
 [-1]]
[[0]
 [0]
 [0]]
[[0]
 [0]
 [0]]
[[-1]
 [ 0]
 [ 0]]
[[-1]
 [-1]
 [ 0]]
[[-1]
 [-1]
 [-1]]
[[0]
 [0]
 [0]]
[[0]
 [0]
 [0]]
[[-1]
 [ 0]
 [ 0]]
[[-1]
 [-1]
 [ 0]]
[[-1]
 [-1]
 [-1]]
[[0]
 [0]
 [0]]
[[0]
 [0]
 [0]]
[[-1]
 [ 0]
 [ 0]]
[[-1]
 [-1]
 [ 0]]
[[-1]
 [-1]
 [-1]]
[[0]
 [0]
 [0]]
[[0]
 [0]
 [0]]
[[-1]
 [ 0]
 [ 0]]
[[-1]
 [-1]
 [ 0]]
[[-1]
 [-1]
 [-1]]
[[0]
 [0]
 [0]]
[[0]
 [0]
 [0]]
[[-1]
 [ 0]
 [ 0]]
[[-1]
 [-1]
 [ 0]]
[[-1]
 [-1]
 [-1]]
[[0]
 [0]
 [0]]
[[0]
 [0]
 [0]]
[[-1]
 [ 0]
 [ 0]]
[[-1]
 [-1]
 [ 0]]
[[-1]
 [-1]
 [-1]]
[[0]
 [0]
 [0]]
[[0]
 [0]
 [0]]
[[-1]
 [ 0]
 [ 0]]
[[-1]
 [-1]
 [ 0]]
[[-1]
 [-1]
 [-1]]
[[0]
 [0]
 [0]

In [11]:
print(res)

(array([[0],
       [0],
       [0]]), 1000, 200)


In [12]:
def perceptron(x: np.array, y: np.array, t: int, tho=None) -> tuple[np.array]:
    """
    Perceptron learning algorithm.
    returns tuple of th and th0.
    """
    
    th = utils.rv([0, 0, 0]) # 3*1
    if tho is not None:
        th = tho

    th0 = 0 # 1*1
    k = 0
    iterations = 0
    for i in range(t):
        iterations = i + 1
        converged = True
        for j in range(x.shape[1]):
            yj = y[j]
            xj = x[:, j:j+1]
            r = yj * (np.dot(th.T, xj) + th0)  
            # print('r', r, yj, xj)
            if r <= 0:
                converged = False
                k+=1
                th = th + yj * xj
                th0 = th0 + yj
        if converged:
            print('errors', k)
            print('iterations', iterations)            
            return th, th0
    print('errors', k)
    print('iterations', iterations)
    return th, th0


res = perceptron(x, y, 200)
print(res)

errors 40
iterations 18
(array([[2],
       [3],
       [4]]), -8)


## 4.2) Families

# 5) Separation

In [13]:
x = np.array([
    [1, -1],
    [1, 1],
    [2, -1],
    [2, 1],
]).T
y = np.array([-1, 1, 1, -1])

res = perceptron_through_the_origin(x, y, 200)
print(res)


[[-1]
 [ 1]]
[[0]
 [2]]
[[2]
 [1]]
[[0]
 [0]]
[[-1]
 [ 1]]
[[0]
 [2]]
[[2]
 [1]]
[[0]
 [0]]
[[-1]
 [ 1]]
[[0]
 [2]]
[[2]
 [1]]
[[0]
 [0]]
[[-1]
 [ 1]]
[[0]
 [2]]
[[2]
 [1]]
[[0]
 [0]]
[[-1]
 [ 1]]
[[0]
 [2]]
[[2]
 [1]]
[[0]
 [0]]
[[-1]
 [ 1]]
[[0]
 [2]]
[[2]
 [1]]
[[0]
 [0]]
[[-1]
 [ 1]]
[[0]
 [2]]
[[2]
 [1]]
[[0]
 [0]]
[[-1]
 [ 1]]
[[0]
 [2]]
[[2]
 [1]]
[[0]
 [0]]
[[-1]
 [ 1]]
[[0]
 [2]]
[[2]
 [1]]
[[0]
 [0]]
[[-1]
 [ 1]]
[[0]
 [2]]
[[2]
 [1]]
[[0]
 [0]]
[[-1]
 [ 1]]
[[0]
 [2]]
[[2]
 [1]]
[[0]
 [0]]
[[-1]
 [ 1]]
[[0]
 [2]]
[[2]
 [1]]
[[0]
 [0]]
[[-1]
 [ 1]]
[[0]
 [2]]
[[2]
 [1]]
[[0]
 [0]]
[[-1]
 [ 1]]
[[0]
 [2]]
[[2]
 [1]]
[[0]
 [0]]
[[-1]
 [ 1]]
[[0]
 [2]]
[[2]
 [1]]
[[0]
 [0]]
[[-1]
 [ 1]]
[[0]
 [2]]
[[2]
 [1]]
[[0]
 [0]]
[[-1]
 [ 1]]
[[0]
 [2]]
[[2]
 [1]]
[[0]
 [0]]
[[-1]
 [ 1]]
[[0]
 [2]]
[[2]
 [1]]
[[0]
 [0]]
[[-1]
 [ 1]]
[[0]
 [2]]
[[2]
 [1]]
[[0]
 [0]]
[[-1]
 [ 1]]
[[0]
 [2]]
[[2]
 [1]]
[[0]
 [0]]
[[-1]
 [ 1]]
[[0]
 [2]]
[[2]
 [1]]
[[0]
 [0]]
[[-1]
 [ 1]]
[[0]
 [2]]
[[2]
 [1]]

In [14]:
x = np.array([
    [1, -1],
    [1, 1],
    [2, -1],
    [2, 1],
]).T
y = np.array([1, 1, -1, -1])

res = perceptron(x, y, 200, utils.rv([0, 0]))
print(res)


errors 18
iterations 8
(array([[-3],
       [ 0]]), 4)


In [15]:
x = np.array([
    [1, -1, 1],
    [1, 1, 1],
    [2, -1, 1],
    [2, 1, 1],
]).T
y = np.array([1, 1, -1, -1])

res = perceptron_through_the_origin(x, y, 200, utils.rv([0, 0, 0]))
print(res)

[[ 1]
 [-1]
 [ 1]]
[[-1]
 [ 0]
 [ 0]]
[[ 0]
 [-1]
 [ 1]]
[[1]
 [0]
 [2]]
[[-1]
 [ 1]
 [ 1]]
[[-3]
 [ 0]
 [ 0]]
[[-2]
 [-1]
 [ 1]]
[[-1]
 [ 0]
 [ 2]]
[[-3]
 [ 1]
 [ 1]]
[[-2]
 [ 0]
 [ 2]]
[[-1]
 [ 1]
 [ 3]]
[[-3]
 [ 2]
 [ 2]]
[[-2]
 [ 1]
 [ 3]]
[[-4]
 [ 0]
 [ 2]]
[[-3]
 [-1]
 [ 3]]
[[-2]
 [ 0]
 [ 4]]
[[-4]
 [ 1]
 [ 3]]
[[-3]
 [ 0]
 [ 4]]
(array([[-3],
       [ 0],
       [ 4]]), 18, 8)


In [16]:
def perceptron(data, labels, params={}, hook=None):
    """
    Perceptron learning algorithm.
    returns tuple of th and th0.
    """
    
    d = len(data)
    n = data.shape[1]
    
    t = params.get('T', 100)
    th = np.zeros((len(data), 1)) # len(data)*1
    th0 = np.zeros((1, 1)) # 1*1
    
    data = data.T
    
    k = 0
    iterations = 0
    for i in range(t):
        iterations = i + 1
        converged = True
        if hook:
            hook(th, th0)
        for j in range(len(data)):
            yj = labels[j]
            xj = data[j].reshape((d, 1))
            r = np.sum(yj * (np.dot(th.T, xj) + th0))  
            print('r', r, yj, xj)
            if r <= 0:
                converged = False
                k+=1
                th = th + yj * xj
                th0 = th0 + yj
        if converged:
            print('errors', k)
            print('iterations', iterations)            
            return th, th0
    print('errors', k)
    print('iterations1', iterations)

    return th, th0

y = np.array([1, 1, -1, -1])

print(np.array([[1, 1, 1, 1]]).shape, y.shape)

(1, 4) (4,)


In [17]:
x = np.array([
    [1, -1, 1],
    [1, 1, 1],
    [2, -1, 1],
    [2, 1, 1],
]).T
y = np.array([1, 1, -1, -1])


perceptron(x, y)

r 0.0 1 [[ 1]
 [-1]
 [ 1]]
r 2.0 1 [[1]
 [1]
 [1]]
r -5.0 -1 [[ 2]
 [-1]
 [ 1]]
r 2.0 -1 [[2]
 [1]
 [1]]
r -1.0 1 [[ 1]
 [-1]
 [ 1]]
r 1.0 1 [[1]
 [1]
 [1]]
r -3.0 -1 [[ 2]
 [-1]
 [ 1]]
r 4.0 -1 [[2]
 [1]
 [1]]
r -2.0 1 [[ 1]
 [-1]
 [ 1]]
r 0.0 1 [[1]
 [1]
 [1]]
r -4.0 -1 [[ 2]
 [-1]
 [ 1]]
r 1.0 -1 [[2]
 [1]
 [1]]
r -1.0 1 [[ 1]
 [-1]
 [ 1]]
r 3.0 1 [[1]
 [1]
 [1]]
r -2.0 -1 [[ 2]
 [-1]
 [ 1]]
r 3.0 -1 [[2]
 [1]
 [1]]
r -2.0 1 [[ 1]
 [-1]
 [ 1]]
r 2.0 1 [[1]
 [1]
 [1]]
r 0.0 -1 [[ 2]
 [-1]
 [ 1]]
r 5.0 -1 [[2]
 [1]
 [1]]
r -3.0 1 [[ 1]
 [-1]
 [ 1]]
r 1.0 1 [[1]
 [1]
 [1]]
r 2.0 -1 [[ 2]
 [-1]
 [ 1]]
r 2.0 -1 [[2]
 [1]
 [1]]
r 1.0 1 [[ 1]
 [-1]
 [ 1]]
r 1.0 1 [[1]
 [1]
 [1]]
r 2.0 -1 [[ 2]
 [-1]
 [ 1]]
r 2.0 -1 [[2]
 [1]
 [1]]
errors 12
iterations 7


(array([[-3.],
        [ 0.],
        [ 2.]]),
 array([[2.]]))

In [18]:
t = np.array([[1, 2, 3]])
t.reshape((3, ))

array([1, 2, 3])

In [19]:
def averaged_perceptron(data, labels, params={}, hook=None):
    """has better stability..."""
    T = params.get('T', 100)
    d, n = data.shape[0], data.shape[1]  
    th, th0 = np.zeros((d, 1)), np.zeros((1, 1))
    ths, th0s = np.zeros((d, 1)), np.zeros((1, 1))
    labels = labels.reshape((n, ))
    for t in range(T):
        for i in range(n):
            x = data[:, i:i+1]
            y = labels[i]
            if y*np.sum(th.T.dot(x) + th0) <= 0:
                th = th + x*y
                th0 = th0 + y
            ths += th
            th0s += th0
    nT = n * T
    return ths/nT, th0s/nT
averaged_perceptron(x, y)


(array([[-2.9225e+00],
        [ 2.5000e-03],
        [ 1.9525e+00]]),
 array([[1.9525]]))

In [20]:
np.sign([[1, -11], [-1, 2]])

array([[ 1, -1],
       [-1,  1]])

In [27]:
k = 10
data = np.ones((2, 101))

n = data.shape[1]

n_chunks, n_rest = n // k, n % k

In [28]:
n_chunks, n_rest

(10, 1)

In [35]:
len(np.array_split(data, n_chunks, axis=0))

10

In [36]:
n_rest_start = n-(n_rest + 1)
n_rest_stop = n
arr, rest = data[:, 0:n_rest_start], data[:, n_rest_start:n_rest_stop]

In [66]:
def get_chunks(data, k):
    n = data.shape[1]
    n_chunks, n_rest = n // k, n % k
    
    n_rest_start = n-(n_rest + 1)
    n_rest_stop = n
    arr, rest = data[:, 0:n_rest_start], data[:, n_rest_start:n_rest_stop]
    chunks = np.array_split(arr, n_chunks, axis=1)
    
    print(chunks[-1], arr.shape)
    chunks[-1] = np.hstack((chunks[-1], rest))
    return chunks

a = get_chunks(data, 12)
len(a), a[-1].shape

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]] (2, 95)


(8, (2, 17))

In [67]:
labels = np.ones((1, 101))
b = get_chunks(labels, 12)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]] (1, 95)


In [68]:
b.pop(2)


array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [69]:
np.concatenate(b, axis=1)

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [74]:
l = [1, 2, 3]
l.insert(1, -2)
l

[1, -2, 2, 3]

In [80]:
# np.hstack((a[0:2], a[3:-1]))
np.concatenate(a[0:2]+a[3:-1])

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
import numpy as np


def get_chunks(data, k):
    n = data.shape[1]
    n_chunks, n_rest = n // k, n % k
    
    n_rest_start = n-(n_rest + 1)
    n_rest_stop = n
    arr, rest = data[:, 0:n_rest_start], data[:, n_rest_start:n_rest_stop]
    chunks = np.array_split(arr, n_chunks, axis=1)

    chunks[-1] = np.hstack((chunks[-1], rest))
    return chunks

def xval_learning_alg(learner, data, labels, k):
    #cross validation of learning algorithm
    data_chunks = get_chunks(data, k)
    label_chunks = get_chunks(labels, k)
    n_chunks = len(data_chunks)
    acc = 0
    for i in range(n_chunks):
        test_x = data_chunks[i]
        test_y = label_chunks[i]

        train_x = np.concatenate(data_chunks[0:i] + data_chunks[i+1:-1], axis=1)
        train_y = np.concatenate(label_chunks[0:i] + label_chunks[i+1:-1], axis=1)
        th, th0 = learner(train_x, train_y)

        acc += score(test_x, test_y, th, th0)
        
    return acc/n_chunks
        
    
def xval_learning_alg(learner, data, labels, k):
    s_data = np.array_split(data, k, axis=1)
    s_labels = np.array_split(labels, k, axis=1)

    score_sum = 0
    for i in range(k):
        data_train = np.concatenate(s_data[:i] + s_data[i+1:], axis=1)
        labels_train = np.concatenate(s_labels[:i] + s_labels[i+1:], axis=1)
        data_test = np.array(s_data[i])
        labels_test = np.array(s_labels[i])
        score_sum += eval_classifier(learner, data_train, labels_train,
                                              data_test, labels_test)
    return score_sum/k
