In [1]:
import numpy as np



In [47]:
# 1.2 Code for distance

def signed_dist(x, theta, theta_0):
    return 1/np.linalg.norm(theta) * (np.dot(theta.T, x) + theta_0)


theta = np.array([[1, 1]]).T
theta_0 = 0
x1 = np.array([[1, 1]]).T
x2 = np.array([[-1, -1]]).T
signed_dist(x1, theta, theta_0),signed_dist(x2, theta, theta_0) 

(array([[1.41421356]]), array([[-1.41421356]]))

In [18]:
# code for side of hyperplane

def positive(x, th, th0):
    d = signed_dist(x, th, th0)
    return np.sign(d)

positive(x1, theta, theta_0), positive(x2, theta, theta_0), positive(np.array([[0, 0]]).T, theta, theta_0)

(array([[1.]]), array([[-1.]]), array([[0.]]))

In [20]:
# 1.4


def rv(value_list):
    return np.array([value_list]).T

# 5*2 -> 2*5 : d*n -> n*d
data = np.transpose(np.array([[1, 2], [1, 3], [2, 1], [1, -1], [2, -1]])) 
# 1*n -> n*1
labels = rv([-1, -1, +1, +1, +1])

A = positive(data, theta, theta_0)
A

array([[1., 1., 1., 0., 1.]])

In [34]:
"""
A should be a 1 by 5 array of boolean values, either True or False,
indicating for each point in data and corresponding label in labels whether it is 
correctly classified by hyperplane th = [1, 1], th0 = -2 . 
That is, return True when the side of the hyperplane (specified by θ\thetaθ, θ0\theta_0θ0​)
that the point is on agrees with the specified label.
"""

th = rv([2, 2])
th0 = -2
A = positive(data, th, th0).T == labels
A, sum(A)

(array([[False],
        [False],
        [ True],
        [False],
        [False]]),
 array([1]))

In [38]:
np.sum(A).tolist()

1

In [39]:
np.sum(np.array([[1,1,1],[2,2,2]]), axis=0), np.sum(np.array([[1,1,1],[2,2,2]]), axis=1)


(array([3, 3, 3]), array([3, 6]))

In [79]:
# 1.6 best separator

"""
data: a d by n array of floats (representing n data points in d dimensions)
labels: a 1 by n array of elements in (+1, -1), representing target labels
ths: a d by m array of floats representing mmm candidate θ\thetaθ\s (each θ\thetaθ has dimension ddd by 1)
th0s: a 1 by m array of the corresponding mmm candidate θ0\theta_0θ0s.
"""

data = np.array([
    [1, 2],
    [1, 1],
    [0, 1],
]) # d*n -> 3*2 n datapoints

labels = np.array([[1,-1, 1]]) # 1*n -> 1*3
ths = np.array([
    [1, 2, 4, 5],
    [1, 3, -1, 2],
]) # d*m -> 2*4
th0s = np.array([[1, 0, 2]])


def score(data, labels, ths, th0s):
    r = positive(data, ths, th0s) == labels
    i = np.argmax(np.sum(r.T, axis=0))
    return ths[:, i:i+1], np.array([th0s[i]])


def best_separator(data, labels, ths, th0s):
    return score(data, labels, ths, th0s.T)

print(score(data.T, labels, ths, th0s))


(array([[1],
       [1]]), array([[1, 0, 2]]))


In [46]:
theta

array([[1],
       [1]])

In [60]:
r = np.array([
    [False, False, True, True, True],
    [False, False, True, True, True],
    [False, False, True, True, True],
    [False, False, False, False, False],
    [True, True, False, True, True], 
    [True, True, True, False, True],
    [True, True, False, True, True],
    [True, True, False, True, True],
    [True, True, False, True, True],
    [True, True, True, True, True]])

In [64]:
i = np.argmax(np.sum(r.T, axis=0))
[
    [
        [0.32548657],
        [-0.83807759]
    ],
    [
        [0.74308104]
    ]
]
[
    [
        [0.32548657, -0.83807759]
    ],
    [
        [0.74308104]
    ]
]

9

In [77]:
k = np.array([
    [1, 2],
    [3, 4],
])


np.array(k[:, 1:2])

array([[2],
       [4]])