In [1]:
import numpy as np

# 2.1
A = np.ones((2, 3))
print(A)

[[1. 1. 1.]
 [1. 1. 1.]]


In [2]:
# 2.2
def tp(A):
    return np.transpose(A), A.T

tp(np.ones((2, 3)))

(array([[1., 1.],
        [1., 1.],
        [1., 1.]]),
 array([[1., 1.],
        [1., 1.],
        [1., 1.]]))

In [5]:
# 2.3a
x, y = np.array([[1], [2], [3], [4]]), np.array([[1], [0], [0], [1]])
(x * y), (x * y).shape

(array([[1],
        [0],
        [0],
        [4]]),
 (4, 1))

In [6]:
# 2.3b
# np.dot(x, y) -> raises Exception


In [8]:
# 2.4d
c = np.ones((4, 1))
np.dot(np.transpose(c), c).shape

(1, 1)

In [11]:
# 2.3f
D = np.array([1, 2, 3])
D.shape

(3,)

In [13]:
# 2.3g 
D = np.array([[1, 2], [1, 3], [1, 4], [1, 5]])
D[:, 1]

array([2, 3, 4, 5])

In [23]:
# 2.3h
D = np.array([[1, 2], [1, 3], [1, 4], [1, 5]])
D[:, 1:2].shape, D[:, 1:2]

((4, 1),
 array([[2],
        [3],
        [4],
        [5]]))

In [24]:
# 2.4 row vector
def rv(r):
    return np.array([r])

rv([1, 2, 3])

array([[1, 2, 3]])

In [25]:
# 2.5 column vector
def cv(value_list):
    return np.array([value_list]).T

cv([1, 2, 3, 4])

array([[1],
       [2],
       [3],
       [4]])

In [31]:
# 2.6 vector length
import numpy as np

def length(col_v):
    return np.math.sqrt(np.dot(col_v.T, col_v))

length(np.array([[1, 2, 3, 4]]).T)


5.477225575051661

In [32]:
# 2.7 normalize

def normalize(col_v):
    return col_v/length(col_v)

normalize(np.array([[4, 0, 0]]).T)

array([[1.],
       [0.],
       [0.]])

In [36]:
# 2.8 final colun 2-D array

def index_final_column(A):
    return np.array([A[:, -1]]).T

index_final_column(np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
]))


array([[3],
       [6],
       [9]])

In [37]:
# 2.9 representing data
# 3 humans data
'''
weight,height
150,5.8
130,5.5
120,5.3
'''
D = np.array([
    [150, 5.8],
    [130, 5.5],
    [120, 5.3],
])


In [38]:
# 2.10 matrix multiplication

def transform(data):
    return np.dot(data, np.array([[1, 1]]).T)

transform(D)

array([[155.8],
       [135.5],
       [125.3]])